### ISSUE TITLE
Why do custom elements need explicit this.render() call to render initially?

### ISSUE THREAD

**Issue by mhoyer** [WebReflection/hyperHTML-Element#13]
Think about this minimal `HyperHTMLElement` derived element implementation:

```es6
class SimpleElement extends HyperHTMLElement {
    render() {
        return this.html`DO IT`;
    }
}
SimpleElement.define('x-simple');
```

I was wondering why this is not working out of the box. Well there must be at least one call of `this.render()` when the component initialized itself. E. g. by overwriting `connectedCallback()` method: 
```es6
class SimpleElement extends HyperHTMLElement {
    connectedCallback() {
        this.render();
    }
    render() {...}
}
``` 

See: https://jsbin.com/xevisiviwa/edit?html,output

But is there any use-case, where it makes sense to *not* render the element initially? Otherwise, can't this be a default implementation in `HyperHTMLElement` class? I can then still override it in my derived class if needed.

**Comment by WebReflection** [comment]
the entry point to render once is `created` method. If I provide you that automatically "you" are going to do `super(); this.render()` within your create, which is a mistake.

The minimal implementation of a class is
```js
class SimpleElement extends HyperHTMLElement {
  created() { this.render(); }
  render() { return this.html`DO IT`; }
}
SimpleElement.define('x-simple');
```

This is already an edge case not worth solving in core because it causes more issues than it solves.

**Comment by WebReflection** [comment]
P.S. worth a note that with `hyper.Component` you don't need to explicitly invoke render, the engine does that for you. Maybe I can do the same for HyperHTMLElement classes, if available, so you can write your minimal version but then you'll have an indirect dependency on the container of your elements which feels dirty.

**Comment by jiayihu** [comment]
I'm starting to explore Custom Elements and hyperHTML, but coming from React, I was too confused by this behaviour. My understanding is that rendering by default is dangerous because my custom element would be rendered, even if I don't use it anywhere.

At first, it's confusing because in React the parent component calls the `render` method for each child to build the virtual DOM, but with Custom Elements the components are "rendered" by declaring them in the HTML template.

Despite my interpretation of the reason, I believe this should be more clear in the documentation. I see that the 1.8 Custom Elements examples has `created() { this.render(); }`, but the main one is missing it and `render()` is called only on attribute change.

**Comment by WebReflection** [comment]
I might fallback to a default created that invokes `this.render()` soon since I agree this might bite even if you come from `hyperHTML.Component`

**Comment by WebReflection** [comment]
FYI `v3.0.0` now implicitly invokes `this.render()` when `created() {...}` is not defined.

If defined, you are still in charge to invoke (or feel free to not do so) `this.render()` within the `created` method.

**Comment by jiayihu** [comment]
That's very cool @WebReflection, thanks!

P.S.
Is there any Slack chat or something else, where to talk about `hyperHTML`? I'm just having some small thoughts, but you can also find me in https://italiajs.herokuapp.com/ if you prefer

**Comment by WebReflection** [comment]
there is a gitter lobby for that
https://gitter.im/viperHTML/Lobby

**Comment by WebReflection** [comment]
@jiayihu I've had a very bad experience in Facebook with the Italian JS community so I might hesitate to find myself again in an env where moderator's friends are more important than any code of conduct ... not sure that's the case in this Slack channel but for the time being I prefer not being involved, thanks for your understanding.

**Comment by jiayihu** [comment]
The Slack community has nothing to do with the FB group, which is a much more worse environment, but I nevertheless understand your reasons. I instead joined the gitter chat!
