### ISSUE TITLE
Error in the documentation or code maybe

### ISSUE THREAD

**Issue by pinguxx** [WebReflection/hyperHTML-Element#17]
The docs says:
```
// this.html`<i onclick=${this.handleClick}>try</i>`;
  handleClick(e) {
    // `this` still refers to the current custom element
    console.log(this, e.type, e.currentTarget, e.target);
  }
```

But in this case this refers to the element clicked not the custom element

see https://codepen.io/pinguxx/pen/POdaMb

**Comment by WebReflection** [comment]
`handleXXX` is the key, this project will never bind every prototype method without a valid reason. `handle` as prefix **is** the valid reason and the documentation says:

> you can also use Preact-like events handling
> this is less efficient, but migration friendly.

I suggest you don't use this pattern anyway, and just use the `onclick` convention and pass `this` right away as listener.

It's a very valid, standard, pattern.
https://medium.com/@WebReflection/dom-handleevent-a-cross-platform-standard-since-year-2000-5bf17287fd38

**Comment by WebReflection** [comment]
```js
class CustomElement extends HyperHTMLElement {
  onclick(e) {
    console.log(this, e.target)
  }
  created() {
    this.html`<span onclick=${this}>click me</span>`;
  }
}

CustomElement.define('custom-element');
```
