### ISSUE TITLE
Safari throws error related to X-Content-Type: nosniff 

### ISSUE THREAD

**Issue by WesleyDRobinson** [WebReflection/hyperHTML-Element#18]
Firstly, I really appreciate this project!
I've been running into an *intermittent* 😢 issue with Safari, and I'm having trouble finding the root.

[Loading clientside from unpkg](https://github.com/WesleyDRobinson/wesley-tech-2018/blob/master/public/index.html#L16-L19)
It catches on the [nav-item component](https://github.com/WesleyDRobinson/wesley-tech-2018/blob/master/src/components/nav-item.js).

Can you help me understand where to apply a solution?
![](https://cloudup.com/c3cMCFpUV_g+)

**Comment by WebReflection** [comment]
sorry I've completely missed this one !!!

to start with, if you include `hyperhtml-element` script you don't need to include `hyperhtml` too.

```js
// example, how to get hyperHTML features with hyper-Element
const {bind, hyper, wire} = HyperHTMLElement;
```

Since January few changes happened too so, if you could show me an example that fails (live or via code) I might be able to help, otherwise I have no idea what could be the cause.

**Comment by WesleyDRobinson** [comment]
No worries! 
It seems I'm the only person who had the issue, and I haven't seen it again (although I don't develop in Safari most of the time)—ok to close.

"you don't need to include `hyperhtml` too" 
Ah, thanks for the note! I get it.
