### ISSUE TITLE
Super expression must either be null or a function, not object

### ISSUE THREAD

**Issue by giotramu** [WebReflection/hyperHTML-Element#19]
I get **"Super expression must either be null or a function, not object"** error when I run index.js:

My **index.js** code:
```
import hyperHTML from 'hyperhtml';
import HyperHTMLElement from 'hyperhtml-element';

class SimpleElement extends HyperHTMLElement {
  created() {
    this.render();
  }

  render() {
    return this.html`DO IT`;
  }
}

SimpleElement.define('x-simple');
```

My **index.html** code:
```
<x-simple></x-simple>
```

My **package.json** file:
http://jsoneditoronline.org/?id=16781014c5a73885d395019ba5fcc317

What have I done wrong?

**Comment by WebReflection** [comment]
As you can see in [this CodePen](https://codepen.io/WebReflection/pen/Zvrmzx?editors=0010) everything is fine.

There are two differences:
  * you don't need `import hyperHTML from 'hyperhtml';` because `hyperhtml` is already part of HyperHTMLElement
  * there is no tools around it

It looks indeed like you are transpiling code but Babel < 7 is not compatible with native extend.

You might need to add an extra step to your transpilation which is this plugin which is included in Babel 7
https://github.com/WebReflection/babel-plugin-transform-builtin-classes
