### ISSUE TITLE
Strange behavior in FF with Shadow Dom

### ISSUE THREAD

**Issue by ryan-edge-ck** [WebReflection/hyperHTML-Element#7]
## Description

In Firefox, calling the `render` function outside of the component constructor causes the children to disappear.

Take the simple example:

```
    class ParentElement extends HyperHTMLElement {
        constructor() {
            super()
            const root = this.attachShadow({ mode: 'open' })

            this.render()
            // root.innerHTML = '<slot></slot>'
        }

        get template() {
            return this.html`<slot></slot>`
        }

        render() {
            return this.template
        }

        connectedCallback() {
            console.log('render')
            // this.render()
        }
    }

    ParentElement.define('parent-element')
```

Adding`render` to `connectedCallback` will break the rendering, however everything works fine if it is called from the constructor.  The workaround I came up with was to assign shadowRoot to a variable outside of the  class and reapply before render.  I'm sure this is not optimal.

For polyfills, I am using *shadydom* with *document-register-element*

**Comment by WebReflection** [comment]
`HyperHTMLElement` has a `created` method which **is** the one to use for setups:

  * no `super()` call needed, which is what breaks in polyfilled/transpiled code
  * you can render anything, including **non ShadowDOM**

https://viperhtml.js.org/hyperhtml/documentation/#components-2

Accordingly, the most basic example you can try is the following one:
```js
class ParentElement extends HyperHTMLElement {
  created() {
    this.attachShadow({ mode: 'open' });
    this.render();
  }
  render() {
    return this.html`<slot></slot>`;
  }
}

ParentElement.define('parent-element')
```

Now, let's move to the next potential issue: since FF doesn't support Custom Elements, neither Shadow DOM, which polyfill are you using?

For Custom Elements there's only [one truly reliable polyfill](https://github.com/WebReflection/document-register-element) that I am aware of, the same used by StencilJS and Google HTML AMP, but it doesn't cover ShadowDOM, which is a very complex, partially broken, polyfill, not everyone needs or should use.

In these cases, I strongly suggest, for best cross-browser compatibility, to just define your template as HTML and forget Shadow DOM.

Until I have these extra details, I'm afraid I cannot help much 'cause my tests on Firefox work well.

**Comment by ryan-edge-ck** [comment]
Verified that moving the shadow functionality into the created callback resolves the issue for Firefox.

The polyfill that I was using for ShadowDOM is [shadydom](https://github.com/webcomponents/shadydom). For my particular case, I needed shadydom to handle `slot` functionality.

**Comment by WebReflection** [comment]
thanks for confirming it works as expected

**Comment by jfbrennan** [comment]
I have several components where I want to use slot, but don't want shadow DOM. This doesn't seem to be an option. Here's what I'm doing:
```javascript
class Nav extends HyperHTMLElement {
  created() {
    // this.attachShadow({ mode: 'open' }); Does not work, only works with shadow DOM :(
    this.render();
  }

  render() {
    return this.html`<nav><slot></slot><nav>...</nav ></nav>`;
  }
}

Nav.define('aui-nav')
```

**Comment by jfbrennan** [comment]
@WebReflection any help on the above would be appreciated. I have another use case for slotting and HyperHTMLElement doesn't seem to slot for light DOM:

```
// Does not work (content does not get slotted)
class MyAlert extends HyperHTMLElement {

  created() {
    //this.attachShadow({ mode: 'open' });
    this.render();
  }

  ...

  render() {
    this.html`
      <slot></slot>
      <button>Close</button>
    `;
  }
}

MyAlert.define('my-alert');
```
```
// Works, but then I'm stuck with shadow DOM :(
class MyAlert extends HyperHTMLElement {

  created() {
    this.attachShadow({ mode: 'open' });
    this.render();
  }

  ...

  render() {
    this.html`
      <slot></slot>
      <button>Close</button>
    `;
  }
}

MyAlert.define('my-alert');
```

**Comment by WebReflection** [comment]
@jfbrennan I'm afraid I have no plan/time to handle slots beside their only useful use case which is with Shadow DOM, so I suggest you either drop slots or simply use what others used too https://github.com/WebReflection/hyperHTML-Element/issues/7#issuecomment-325737594
